const bookstoreTemplate = {
  id: "bookstore",
  name: "Bookstore",
  version: "1.0.0",
  description: "Reusable printed-book selling ecommerce template with catalog, cart, checkout, enquiries, gallery and admin-ready data hooks.",
  featureCount: 30,
  features: {
    hero: true,
    trustBadges: true,
    offers: true,
    catalogSearch: true,
    categoryFilter: true,
    priceFilter: true,
    sorting: true,
    bookDetails: true,
    amazonLinks: true,
    cart: true,
    checkout: true,
    deliveryDistancePricing: true,
    multiplePaymentMethods: true,
    codToggle: true,
    orderSuccess: true,
    orderTrackingHook: true,
    gallery: true,
    enquiry: true,
    whatsapp: true,
    phone: true,
    maps: true,
    mobileBottomNav: true,
    adminDashboard: true,
    adminAnalytics: true,
    adminHomeEditor: true,
    adminBooksCrud: true,
    adminOrders: true,
    adminDeliverySettings: true,
    adminOffers: true,
    adminGalleryManager: true,
    adminEnquiries: true,
    seoSettings: true,
    securitySettings: true,
    resetDemoStore: true,
    cinematicHeroSlot: true
  },
  pages: ["index.html", "cart.html", "checkout.html", "enquiry.html", "gallery.html", "success.html", "admin.html"],
  settings: {
    currency: "₹",
    staticDemoMode: true,
    backendReady: true
  }
};

export default bookstoreTemplate;
